[build]
  command = "yarn && npm run bootstrap && npm run build && npm run build:site"
  publish = "packages/site/public"

[build.environment]
  NODE_VERSION = "8"
  YARN_VERSION = "1.2.1"
  YARN_FLAGS = "--pure-lockfile"